---
- name: download java sdk.
  shell: sh /vagrant/ansible/roles/java/files/download.sh {{ jdk.url }} {{ jdk.pkg }}
  args:
    chdir: /tmp
    creates: /tmp/{{ jdk.pkg }}

- name: install JAVA SDK
  yum: name=/tmp/{{ jdk.pkg }} state=present