- name: groups create
  group: >
    name={{ item.group }}
    state=present
  with_items: addusers
- name: users create
  user: >
    name={{ item.username }}
    password={{ item.password }}
    group={{ item.group }}
    shell={{ item.shell }}
    home={{ item.home }}
    createhome=yes
    state=present
  with_items: addusers