---
- name: 'install-pkg | RedHat | Each package for development should be installed'
  yum:  name={{ item }} state=present
  with_items:
    - autoconf
    - automake
    - gcc
    - gcc-c++
    - gettext
    - gettext-devel
    - git
    - ncurses
    - ncurses-devel
    - openssl-devel
    - patch
    - pcre
    - pcre-devel
    - readline
    - readline-devel

- name: 'install-pkg | RedHat | Each package for archive should be installed'
  yum:  name={{ item }} state=present
  with_items:
    - bzip2
    - zip
    - zlib
    - zlib-devel

- name: 'install-pkg | Each tool should be installed'
  yum:  name={{ item }} state=present
  with_items:
    - wget
    - telnet
    - finger